#!/usr/bin/env bash
#
# smoke-tiny-elf-host.sh — run a minimal runnable-lift lift NATIVELY on the
# Ubuntu 24.04 host, against the binary produced by build-runnable-lift-host.sh.
#
# It compiles a tiny static ELF (a single exit syscall), lifts it to LLVM IR
# with the freshly built runnable-lift, and asserts the IR is non-empty and the
# lift reports success. No Docker.
#
# Usage:
#   bash runnable/scripts/host-build/smoke-tiny-elf-host.sh [--binary PATH]
#
# Options:
#   --binary PATH   runnable-lift binary to test.
#                   Default: build-codex-dynamic-current/tools/runnable-lift/runnable-lift
#   --scratch DIR   scratch directory. Default: /tmp/rr-host-smoke
#
# Prereqs: run build-runnable-lift-host.sh first.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# host-build -> scripts -> runnable -> repo root
RR_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd -P)"

BUILD_DIR="build-codex-dynamic-current"
RUNNABLE_LIFT=""
SCRATCH="/tmp/rr-host-smoke"

usage() {
  cat <<EOF
Usage:
  bash $(basename "${BASH_SOURCE[0]}") [options]

Options:
  --binary PATH   runnable-lift binary. Default:
                  build-codex-dynamic-current/tools/runnable-lift/runnable-lift
  --scratch DIR   scratch directory. Default: $SCRATCH
  -h, --help      Show this help.
EOF
}

die() { echo "error: $*" >&2; exit 1; }
note() { printf '\n== %s ==\n' "$*"; }

find_llvm_config_tool() {
  local tool
  for tool in llvm-config llvm-config-18 llvm-config-17 llvm-config-16; do
    if command -v "$tool" >/dev/null 2>&1; then
      printf '%s\n' "$tool"
      return 0
    fi
  done
  return 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --binary) RUNNABLE_LIFT="${2:?missing value for --binary}"; shift 2 ;;
    --scratch) SCRATCH="${2:?missing value for --scratch}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

# Resolve the binary path (repo-relative or absolute).
if [[ -z "$RUNNABLE_LIFT" ]]; then
  RUNNABLE_LIFT="$RR_DIR/$BUILD_DIR/tools/runnable-lift/runnable-lift"
elif [[ "$RUNNABLE_LIFT" != /* ]]; then
  RUNNABLE_LIFT="$RR_DIR/$RUNNABLE_LIFT"
fi
[[ -x "$RUNNABLE_LIFT" ]] || die "runnable-lift binary not found or not executable: $RUNNABLE_LIFT"

# Compute LD_LIBRARY_PATH from the binary's build tree (parent of the lift dir).
LIFT_DIR="$(cd "$(dirname "$RUNNABLE_LIFT")" && pwd -P)"
BUILD_ROOT="$(cd "$LIFT_DIR/.." && pwd -P)"
LD_PATH="$BUILD_ROOT/lib/StackAnalysis:$BUILD_ROOT/lib/BasicAnalyses:$BUILD_ROOT/lib/Support"
if LLVM_CONFIG_TOOL="$(find_llvm_config_tool)"; then
  LLVM_LIBDIR="$("$LLVM_CONFIG_TOOL" --libdir)"
  if [[ -d "$LLVM_LIBDIR" ]]; then
    LD_PATH="$LD_PATH:$LLVM_LIBDIR"
  fi
fi
if [[ -d "$RR_DIR/root/lib" ]]; then
  LD_PATH="$LD_PATH:$RR_DIR/root/lib"
fi

# Confirm the libtinycode runtime artifacts are next to the binary, otherwise
# the lift will abort with "Couldn't find libtinycode and the helpers".
note "Check runtime artifacts next to binary"
for f in libtinycode-x86_64.so libtinycode-helpers-x86_64.ll early-linked-x86_64.ll; do
  if [[ ! -e "$LIFT_DIR/$f" ]]; then
    cat >&2 <<EOF
error: missing runtime artifact next to the binary:
      $LIFT_DIR/$f

  runnable-lift dlopens libtinycode at runtime. These artifacts are produced by
  the classic QEMU build (support/components/qemu.mk), not by runnable's CMake,
  and are not git-tracked. Stage them from an existing runnable environment:

      cp <existing>/libtinycode-x86_64.so       "$LIFT_DIR/"
      cp <existing>/libtinycode-helpers-x86_64.ll "$LIFT_DIR/"
      # early-linked-x86_64.ll is generated by the build; if absent, rerun
      # build-runnable-lift-host.sh (it is an ALL CMake target).

  See BUILD-HOST-UBUNTU-24.04.md.
EOF
    exit 1
  fi
  echo "  ok: $f"
done

mkdir -p "$SCRATCH"

note "Build tiny static ELF"
ASM="$SCRATCH/rr-host-smoke.S"
ELF="$SCRATCH/rr-host-smoke"
cat >"$ASM" <<'EOF'
.global _start
.text
_start:
  mov $60, %rax
  xor %rdi, %rdi
  syscall
EOF
gcc -nostdlib -static -Wl,-e,_start "$ASM" -o "$ELF"
[[ -x "$ELF" ]] || die "failed to compile tiny ELF"
echo "  $ELF"

note "Lift tiny ELF with runnable-lift (host, no Docker)"
OUT_LL="$SCRATCH/rr-host-smoke.ll"
OUT_STDOUT="$SCRATCH/rr-host-smoke.stdout"
OUT_STDERR="$SCRATCH/rr-host-smoke.stderr"

LD_LIBRARY_PATH="$LD_PATH${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
  "$RUNNABLE_LIFT" "$ELF" "$OUT_LL" -no-link \
  >"$OUT_STDOUT" 2>"$OUT_STDERR" || {
    echo "--- runnable-lift stdout ---"; cat "$OUT_STDOUT"
    echo "--- runnable-lift stderr ---"; cat "$OUT_STDERR"
    die "runnable-lift exited non-zero"
  }

note "Verify lift output"
[[ -s "$OUT_LL" ]] || die "lift produced an empty .ll: $OUT_LL"
if ! grep -q "Rewrite Successful" "$OUT_STDOUT"; then
  echo "--- runnable-lift stdout ---"; cat "$OUT_STDOUT"
  echo "--- runnable-lift stderr ---"; cat "$OUT_STDERR"
  die "expected 'Rewrite Successful' in runnable-lift stdout, not found"
fi

echo "  IR bytes : $(wc -c <"$OUT_LL")"
echo "  IR lines : $(wc -l <"$OUT_LL")"
echo "  stdout   : $OUT_STDOUT"
echo "  stderr   : $OUT_STDERR"

echo
echo "TINY_ELF_LIFT_SMOKE=pass"
echo "RUNNABLE_LIFT=$RUNNABLE_LIFT"
